#!/usr/bin/env python3
"""Host-side build fingerprint generator matching build_fingerprint.cpp exactly."""
import pathlib
import re
import sys
import zlib

def normalize_content(data: bytes) -> bytes:
    return re.sub(rb"\r+\n", b"\n", data)

def fingerprint(root: pathlib.Path, manifest: pathlib.Path):
    manifest_bytes = manifest.read_bytes().replace(b"\r", b"")
    crc = 0xFFFFFFFF
    files = 0
    for raw_line in manifest_bytes.split(b"\n"):
        if not raw_line:
            continue
        relative = raw_line.decode("utf-8")
        content = (root / relative).read_bytes()
        crc = zlib.crc32(relative.encode("utf-8"), crc) & 0xFFFFFFFF
        crc = zlib.crc32(b"\x00", crc) & 0xFFFFFFFF
        crc = zlib.crc32(normalize_content(content), crc) & 0xFFFFFFFF
        crc = zlib.crc32(b"\x00", crc) & 0xFFFFFFFF
        files += 1
    return crc ^ 0xFFFFFFFF, files

def main(argv):
    print_mode = len(argv) == 4 and argv[1] == "--print"
    if len(argv) != 4:
        print("usage: build_fingerprint.py <GeneralsMD/Code> <manifest> <header>", file=sys.stderr)
        print("       build_fingerprint.py --print <GeneralsMD/Code> <manifest>", file=sys.stderr)
        return 2
    root = pathlib.Path(argv[2 if print_mode else 1])
    manifest = pathlib.Path(argv[3 if print_mode else 2])
    try:
        value, files = fingerprint(root, manifest)
    except OSError as exc:
        print(f"build_fingerprint.py: {exc}", file=sys.stderr)
        return 1
    if print_mode:
        print(f"0x{value:08X} {files}")
        return 0
    header = (
        "// Generated by Tools/fingerprint/build_fingerprint.cpp at build time: do not edit.\n"
        f"// CRC-32 over the {files} files BuildFingerprint.manifest lists (N1, decision 5).\n"
        "#pragma once\n"
        f"#define ZH_BUILD_FINGERPRINT 0x{value:08X}u\n"
        f"#define ZH_BUILD_FINGERPRINT_FILES {files}u\n"
    )
    output = pathlib.Path(argv[3])
    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        if output.exists() and output.read_text(encoding="utf-8") == header:
            return 0
        output.write_text(header, encoding="utf-8", newline="")
    except OSError as exc:
        print(f"build_fingerprint.py: {exc}", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
